"""Add followed_id to Follow model

Revision ID: 10945c8cb80d
Revises: 
Create Date: 2026-03-09 09:41:29.113795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10945c8cb80d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['followed_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('followed_id')

    # ### end Alembic commands ###
